// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4iauV8bcQNuTk4CgPQ6rdocswd-fh3Ok',
    appId: '1:671589265068:web:daf3ec6431b4682e50b909',
    messagingSenderId: '671589265068',
    projectId: 'styleconnect-25e1c',
    authDomain: 'styleconnect-25e1c.firebaseapp.com',
    storageBucket: 'styleconnect-25e1c.firebasestorage.app',
    measurementId: 'G-ZBERKJ09FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SKoX64iSwoOVwq-aV4bt0jaEIxUQ2J8',
    appId: '1:671589265068:android:70ddfd05b591991450b909',
    messagingSenderId: '671589265068',
    projectId: 'styleconnect-25e1c',
    storageBucket: 'styleconnect-25e1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX4IFF8F5CJnjtx3Fg3wmYoj2r4s1Wi50',
    appId: '1:671589265068:ios:948af7a5690c9ebd50b909',
    messagingSenderId: '671589265068',
    projectId: 'styleconnect-25e1c',
    storageBucket: 'styleconnect-25e1c.firebasestorage.app',
    iosClientId: '671589265068-msfg1m3h1kj8na5roirp40daipe85q9r.apps.googleusercontent.com',
    iosBundleId: 'com.styleconnect.styleconnect',
  );
}
